appVersion: ENC[AES256_GCM,data:PmvZCBQ=,iv:htGPV1JhhmPIOCN3WkcKM27E/OjzjmOAixrFfRHOLyw=,tag:gLTeS4QPzWqVCc0gEbEh8w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:835357571861:key/50fbf41f-9e3d-4978-b720-4f83e1123260
          created_at: "2023-01-20T22:44:11Z"
          enc: AQICAHgkhWz8ncHFwUCv22/Z1pXiIOY9BZ+qhjWSX9iP7Md3xAGewxUTpEgzx4wvKqSLNY1nAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNOrGCdyK93zKdx+7AgEQgDuecJzd/ymKaoreDL2UzUg7pDMhWdTuGwo04JJIAphbJ18fLSTItKzTc+lATBmtYPC0wg+f6ZHkgsuDFQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-20T22:44:11Z"
    mac: ENC[AES256_GCM,data:qWiIOwfvJnwCEeExhA0+uhpQ0T6QPdS42B70asZpgjQhaLtvUmIbE2Eiq6/NFPzZlhubD2cIZ54Hu4md2/9zw8kaz3uMgicTHG7x+FxHTSlYVqPx8gTbRX5acggH9KGaTfyPPqFT/kFLvKDTi59qwOyUyBwNHMe7ygR/qa5guVY=,iv:e2FmhGl8hux7drJnERFsIWC69NjKWmWgwR/n5KmaeY0=,tag:xZ1Y6zmpHD3VGaITKATCDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
